import numpy as np

# Simulation Parameters

BANDWIDTH_WIRELESS_CHANNEL_B = 1  # MHz
BLADE_PROFILE_POWER_PB = 80  # w
INDUCED_POWER_PI = 90  # w
TIP_SPEED_BLADE_UT = 12  # m/s
MEAN_INDUCED_SPEED_V0 = 4  # m/s
FUSELAGE_DRAG_PROPORTION_F0 = 0.6
ROTOR_SOLIDITY_S = 0.05
AIR_DENSITY_RHO = 1.225  # kg/m^3
ROTOR_DISC_AREA_A = 0.503  # m^2
AWGN_POWER_UAV_RECEIVER_N0 = -100  # dBm
POWER_CONSUMPTION_WEIGHT_UES_XI = 10
POWER_CONSUMPTION_WEIGHT_UAVS_ETA = 1
MAXIMAL_TRANSMISSION_POWER_UES_P_TR_MAX = 20  # dBm
NUMBER_TRANSMISSION_POWER_LEVELS_LP = 5
AVERAGE_PENALTY_CONSTANT_EACH_VIOLATION_RP = -100
NUMBER_HIDDEN_LAYERS = 3
LEARNING_RATE_ALPHA_L = 0.01
DISCOUNT_FACTOR_GAMMA = 0.7
REPLAY_MEMORY_SIZE_M = 2000
BATCH_SIZE_NB = 256
GREEDY_PROBABILITY_EPSILON = 0.9
EXPLORATION_INCREMENT_DELTA = 10**-4
DEVIATION_GAUSSIAN_NOISE_SIGMA = 10**-3
FREQUENCY_CARRIER_F = 2e9

NUM_UES_K = 100
NUM_UAVS_N = 10
NUM_TIME_SLOTS_T = 10
RECTANGULAR_AREA_SIDE_LENGTH = 2000  # m (ratio, implies side length of 2000m x 2000m if square, or one side is 2000m)
UE_MOBILITY_ANGLE_CONSTRAINT = [0, 2 * np.pi]  # radians, [0, 2pi]
UE_MOBILITY_VELOCITY_CONSTRAINT = [0, 1]  # m/s
UAV_CIRCULAR_PATTERN_RADIUS_R = 300  # m
UAV_HEIGHT_H = 50  # m
UAV_VELOCITY_V = 4  # m/s
COMPUTATIONAL_CONSTANT_S = 10**-20  # s1 = s2 = ... = sN
OMEGA = 2  # omega1 = omega2 = ... = omegaN
TIME_INTERVAL_PER_SLOT = 1  # s
MAXIMAL_LATENCY_CONSTRAINT_TC = 1  # s
TOTAL_DATA_SIZE_D = 100  # Kbits
TOTAL_CPU_CYCLES_F = 10**7  # CPU cycles
MAX_CONNECTED_UES_PER_UAV_C_MAX = 30
MAX_COMPUTATION_CAPACITY_UAV_F_MAX = 10**9  # CPU cycles/s
UE_COMPUTATION_CAPACITY_FI0_RANGE = [10**4, 10**5]  # cycles/s
